version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: uc-hub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - uc-hub-network

  redis:
    image: redis:6.2
    container_name: uc-hub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - uc-hub-network

  backend:
    build:
      context: ../../backend
      dockerfile: ../infra/docker/Dockerfile.backend
    container_name: uc-hub-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/uc-hub?authSource=admin
      - JWT_SECRET=development_jwt_secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ../../backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - uc-hub-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infra/docker/Dockerfile.frontend
    container_name: uc-hub-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/graphql
    volumes:
      - ../../frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - uc-hub-network

volumes:
  mongodb_data:
  redis_data:

networks:
  uc-hub-network:
    driver: bridge
