apiVersion: v1
kind: Service
metadata:
  name: uc-hub-backend-service
  labels:
    app: uc-hub
    tier: backend
spec:
  selector:
    app: uc-hub
    tier: backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: uc-hub-frontend-service
  labels:
    app: uc-hub
    tier: frontend
spec:
  selector:
    app: uc-hub
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
