apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uc-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Defi-Oracle-Tooling/uc-hub.git
    targetRevision: HEAD
    path: infra/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: uc-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
